---
- job:
    name: kollacli-tox-functional-py36
    parent: openstack-tox
    description: |
      Run tox-based py36 functional tests for the OpenStack Kolla-cli project.
      Uses tox with the ``functional`` environment.
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/source/.*$
      - ^releasenotes/.*$
    vars:
      tox_envlist: functional-py36
    timeout: 3600

- job:
    name: kollacli-tox-mypy
    parent: openstack-tox
    description: |
      Run static mypy type checker for the OpenStack Kolla-cli project.
    vars:
      tox_envlist: mypy
    timeout: 3600

- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - kollacli-tox-mypy
        - kollacli-tox-functional-py36
    gate:
      jobs:
        - kollacli-tox-mypy
        - kollacli-tox-functional-py36
